export const TODOS_REQUEST = 'TODOS_REQUEST';
export const TODOS_REQUEST_SUCCESS = 'TODOS_REQUEST_SUCCESS';
export const TODOS_REQUEST_FAILURE = 'TODOS_REQUEST_FAILURE';
export const ADD_TODO = 'ADD_TODO';
export const GET_TODO = 'GET_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
